// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: proto/heist.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int32                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentRequest) Reset() {
	*x = PaymentRequest{}
	mi := &file_proto_heist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentRequest) ProtoMessage() {}

func (x *PaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentRequest.ProtoReflect.Descriptor instead.
func (*PaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_heist_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type PaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	CorrectAmount bool                   `protobuf:"varint,2,opt,name=correct_amount,json=correctAmount,proto3" json:"correct_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentResponse) Reset() {
	*x = PaymentResponse{}
	mi := &file_proto_heist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentResponse) ProtoMessage() {}

func (x *PaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentResponse.ProtoReflect.Descriptor instead.
func (*PaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_heist_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PaymentResponse) GetCorrectAmount() bool {
	if x != nil {
		return x.CorrectAmount
	}
	return false
}

type OfferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requester     string                 `protobuf:"bytes,1,opt,name=requester,proto3" json:"requester,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfferRequest) Reset() {
	*x = OfferRequest{}
	mi := &file_proto_heist_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferRequest) ProtoMessage() {}

func (x *OfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heist_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferRequest.ProtoReflect.Descriptor instead.
func (*OfferRequest) Descriptor() ([]byte, []int) {
	return file_proto_heist_proto_rawDescGZIP(), []int{2}
}

func (x *OfferRequest) GetRequester() string {
	if x != nil {
		return x.Requester
	}
	return ""
}

type OfferResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HasOffer        bool                   `protobuf:"varint,1,opt,name=has_offer,json=hasOffer,proto3" json:"has_offer,omitempty"`
	Loot            int32                  `protobuf:"varint,2,opt,name=loot,proto3" json:"loot,omitempty"`
	SuccessFranklin int32                  `protobuf:"varint,3,opt,name=success_franklin,json=successFranklin,proto3" json:"success_franklin,omitempty"`
	SuccessTrevor   int32                  `protobuf:"varint,4,opt,name=success_trevor,json=successTrevor,proto3" json:"success_trevor,omitempty"`
	PoliceRisk      int32                  `protobuf:"varint,5,opt,name=police_risk,json=policeRisk,proto3" json:"police_risk,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OfferResponse) Reset() {
	*x = OfferResponse{}
	mi := &file_proto_heist_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferResponse) ProtoMessage() {}

func (x *OfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heist_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferResponse.ProtoReflect.Descriptor instead.
func (*OfferResponse) Descriptor() ([]byte, []int) {
	return file_proto_heist_proto_rawDescGZIP(), []int{3}
}

func (x *OfferResponse) GetHasOffer() bool {
	if x != nil {
		return x.HasOffer
	}
	return false
}

func (x *OfferResponse) GetLoot() int32 {
	if x != nil {
		return x.Loot
	}
	return 0
}

func (x *OfferResponse) GetSuccessFranklin() int32 {
	if x != nil {
		return x.SuccessFranklin
	}
	return 0
}

func (x *OfferResponse) GetSuccessTrevor() int32 {
	if x != nil {
		return x.SuccessTrevor
	}
	return 0
}

func (x *OfferResponse) GetPoliceRisk() int32 {
	if x != nil {
		return x.PoliceRisk
	}
	return 0
}

type DecisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requester     string                 `protobuf:"bytes,1,opt,name=requester,proto3" json:"requester,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionRequest) Reset() {
	*x = DecisionRequest{}
	mi := &file_proto_heist_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionRequest) ProtoMessage() {}

func (x *DecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heist_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionRequest.ProtoReflect.Descriptor instead.
func (*DecisionRequest) Descriptor() ([]byte, []int) {
	return file_proto_heist_proto_rawDescGZIP(), []int{4}
}

func (x *DecisionRequest) GetRequester() string {
	if x != nil {
		return x.Requester
	}
	return ""
}

func (x *DecisionRequest) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type DecisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionResponse) Reset() {
	*x = DecisionResponse{}
	mi := &file_proto_heist_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionResponse) ProtoMessage() {}

func (x *DecisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heist_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionResponse.ProtoReflect.Descriptor instead.
func (*DecisionResponse) Descriptor() ([]byte, []int) {
	return file_proto_heist_proto_rawDescGZIP(), []int{5}
}

func (x *DecisionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Character     string                 `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	PoliceRisk    int32                  `protobuf:"varint,2,opt,name=police_risk,json=policeRisk,proto3" json:"police_risk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StarRequest) Reset() {
	*x = StarRequest{}
	mi := &file_proto_heist_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarRequest) ProtoMessage() {}

func (x *StarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heist_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarRequest.ProtoReflect.Descriptor instead.
func (*StarRequest) Descriptor() ([]byte, []int) {
	return file_proto_heist_proto_rawDescGZIP(), []int{6}
}

func (x *StarRequest) GetCharacter() string {
	if x != nil {
		return x.Character
	}
	return ""
}

func (x *StarRequest) GetPoliceRisk() int32 {
	if x != nil {
		return x.PoliceRisk
	}
	return 0
}

type StarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StarResponse) Reset() {
	*x = StarResponse{}
	mi := &file_proto_heist_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarResponse) ProtoMessage() {}

func (x *StarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heist_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarResponse.ProtoReflect.Descriptor instead.
func (*StarResponse) Descriptor() ([]byte, []int) {
	return file_proto_heist_proto_rawDescGZIP(), []int{7}
}

func (x *StarResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Character     string                 `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_proto_heist_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heist_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_proto_heist_proto_rawDescGZIP(), []int{8}
}

func (x *StopRequest) GetCharacter() string {
	if x != nil {
		return x.Character
	}
	return ""
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_proto_heist_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heist_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_proto_heist_proto_rawDescGZIP(), []int{9}
}

func (x *StopResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DistractionRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequiredTurns     int32                  `protobuf:"varint,1,opt,name=required_turns,json=requiredTurns,proto3" json:"required_turns,omitempty"`
	AssignedCharacter string                 `protobuf:"bytes,2,opt,name=assigned_character,json=assignedCharacter,proto3" json:"assigned_character,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DistractionRequest) Reset() {
	*x = DistractionRequest{}
	mi := &file_proto_heist_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistractionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistractionRequest) ProtoMessage() {}

func (x *DistractionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heist_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistractionRequest.ProtoReflect.Descriptor instead.
func (*DistractionRequest) Descriptor() ([]byte, []int) {
	return file_proto_heist_proto_rawDescGZIP(), []int{10}
}

func (x *DistractionRequest) GetRequiredTurns() int32 {
	if x != nil {
		return x.RequiredTurns
	}
	return 0
}

func (x *DistractionRequest) GetAssignedCharacter() string {
	if x != nil {
		return x.AssignedCharacter
	}
	return ""
}

type DistractionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistractionResponse) Reset() {
	*x = DistractionResponse{}
	mi := &file_proto_heist_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistractionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistractionResponse) ProtoMessage() {}

func (x *DistractionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heist_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistractionResponse.ProtoReflect.Descriptor instead.
func (*DistractionResponse) Descriptor() ([]byte, []int) {
	return file_proto_heist_proto_rawDescGZIP(), []int{11}
}

func (x *DistractionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DistractionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GolpeRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequiredTurns     int32                  `protobuf:"varint,1,opt,name=required_turns,json=requiredTurns,proto3" json:"required_turns,omitempty"`
	AssignedCharacter string                 `protobuf:"bytes,2,opt,name=assigned_character,json=assignedCharacter,proto3" json:"assigned_character,omitempty"`
	PoliceRisk        int32                  `protobuf:"varint,3,opt,name=police_risk,json=policeRisk,proto3" json:"police_risk,omitempty"`
	BaseLoot          int32                  `protobuf:"varint,4,opt,name=base_loot,json=baseLoot,proto3" json:"base_loot,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GolpeRequest) Reset() {
	*x = GolpeRequest{}
	mi := &file_proto_heist_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GolpeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GolpeRequest) ProtoMessage() {}

func (x *GolpeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heist_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GolpeRequest.ProtoReflect.Descriptor instead.
func (*GolpeRequest) Descriptor() ([]byte, []int) {
	return file_proto_heist_proto_rawDescGZIP(), []int{12}
}

func (x *GolpeRequest) GetRequiredTurns() int32 {
	if x != nil {
		return x.RequiredTurns
	}
	return 0
}

func (x *GolpeRequest) GetAssignedCharacter() string {
	if x != nil {
		return x.AssignedCharacter
	}
	return ""
}

func (x *GolpeRequest) GetPoliceRisk() int32 {
	if x != nil {
		return x.PoliceRisk
	}
	return 0
}

func (x *GolpeRequest) GetBaseLoot() int32 {
	if x != nil {
		return x.BaseLoot
	}
	return 0
}

type GolpeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GolpeResponse) Reset() {
	*x = GolpeResponse{}
	mi := &file_proto_heist_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GolpeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GolpeResponse) ProtoMessage() {}

func (x *GolpeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heist_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GolpeResponse.ProtoReflect.Descriptor instead.
func (*GolpeResponse) Descriptor() ([]byte, []int) {
	return file_proto_heist_proto_rawDescGZIP(), []int{13}
}

func (x *GolpeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GolpeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Character     string                 `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_heist_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heist_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_heist_proto_rawDescGZIP(), []int{14}
}

func (x *StatusRequest) GetCharacter() string {
	if x != nil {
		return x.Character
	}
	return ""
}

type StatusResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// "waiting", "working", "success", "failed"
	TurnsCompleted int32 `protobuf:"varint,2,opt,name=turns_completed,json=turnsCompleted,proto3" json:"turns_completed,omitempty"`
	TotalTurns     int32 `protobuf:"varint,3,opt,name=total_turns,json=totalTurns,proto3" json:"total_turns,omitempty"`
	CurrentStars   int32 `protobuf:"varint,4,opt,name=current_stars,json=currentStars,proto3" json:"current_stars,omitempty"`
	ExtraLoot      int32 `protobuf:"varint,5,opt,name=extra_loot,json=extraLoot,proto3" json:"extra_loot,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_heist_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heist_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_heist_proto_rawDescGZIP(), []int{15}
}

func (x *StatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusResponse) GetTurnsCompleted() int32 {
	if x != nil {
		return x.TurnsCompleted
	}
	return 0
}

func (x *StatusResponse) GetTotalTurns() int32 {
	if x != nil {
		return x.TotalTurns
	}
	return 0
}

func (x *StatusResponse) GetCurrentStars() int32 {
	if x != nil {
		return x.CurrentStars
	}
	return 0
}

func (x *StatusResponse) GetExtraLoot() int32 {
	if x != nil {
		return x.ExtraLoot
	}
	return 0
}

type LootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Character     string                 `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LootRequest) Reset() {
	*x = LootRequest{}
	mi := &file_proto_heist_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LootRequest) ProtoMessage() {}

func (x *LootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heist_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LootRequest.ProtoReflect.Descriptor instead.
func (*LootRequest) Descriptor() ([]byte, []int) {
	return file_proto_heist_proto_rawDescGZIP(), []int{16}
}

func (x *LootRequest) GetCharacter() string {
	if x != nil {
		return x.Character
	}
	return ""
}

type LootResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FinalLoot     int32                  `protobuf:"varint,1,opt,name=final_loot,json=finalLoot,proto3" json:"final_loot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LootResponse) Reset() {
	*x = LootResponse{}
	mi := &file_proto_heist_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LootResponse) ProtoMessage() {}

func (x *LootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heist_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LootResponse.ProtoReflect.Descriptor instead.
func (*LootResponse) Descriptor() ([]byte, []int) {
	return file_proto_heist_proto_rawDescGZIP(), []int{17}
}

func (x *LootResponse) GetFinalLoot() int32 {
	if x != nil {
		return x.FinalLoot
	}
	return 0
}

type FinalReport struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MissionOutcome  string                 `protobuf:"bytes,1,opt,name=mission_outcome,json=missionOutcome,proto3" json:"mission_outcome,omitempty"` // "success" or "failed"
	TotalLoot       int32                  `protobuf:"varint,2,opt,name=total_loot,json=totalLoot,proto3" json:"total_loot,omitempty"`
	MichaelShare    int32                  `protobuf:"varint,3,opt,name=michael_share,json=michaelShare,proto3" json:"michael_share,omitempty"`
	FranklinShare   int32                  `protobuf:"varint,4,opt,name=franklin_share,json=franklinShare,proto3" json:"franklin_share,omitempty"`
	TrevorShare     int32                  `protobuf:"varint,5,opt,name=trevor_share,json=trevorShare,proto3" json:"trevor_share,omitempty"`
	LesterShare     int32                  `protobuf:"varint,6,opt,name=lester_share,json=lesterShare,proto3" json:"lester_share,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CharacterFailed string                 `protobuf:"bytes,8,opt,name=character_failed,json=characterFailed,proto3" json:"character_failed,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FinalReport) Reset() {
	*x = FinalReport{}
	mi := &file_proto_heist_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalReport) ProtoMessage() {}

func (x *FinalReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heist_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalReport.ProtoReflect.Descriptor instead.
func (*FinalReport) Descriptor() ([]byte, []int) {
	return file_proto_heist_proto_rawDescGZIP(), []int{18}
}

func (x *FinalReport) GetMissionOutcome() string {
	if x != nil {
		return x.MissionOutcome
	}
	return ""
}

func (x *FinalReport) GetTotalLoot() int32 {
	if x != nil {
		return x.TotalLoot
	}
	return 0
}

func (x *FinalReport) GetMichaelShare() int32 {
	if x != nil {
		return x.MichaelShare
	}
	return 0
}

func (x *FinalReport) GetFranklinShare() int32 {
	if x != nil {
		return x.FranklinShare
	}
	return 0
}

func (x *FinalReport) GetTrevorShare() int32 {
	if x != nil {
		return x.TrevorShare
	}
	return 0
}

func (x *FinalReport) GetLesterShare() int32 {
	if x != nil {
		return x.LesterShare
	}
	return 0
}

func (x *FinalReport) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *FinalReport) GetCharacterFailed() string {
	if x != nil {
		return x.CharacterFailed
	}
	return ""
}

type ReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_proto_heist_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heist_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_heist_proto_rawDescGZIP(), []int{19}
}

func (x *ReportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_heist_proto protoreflect.FileDescriptor

const file_proto_heist_proto_rawDesc = "" +
	"\n" +
	"\x11proto/heist.proto\x12\x05heist\"(\n" +
	"\x0ePaymentRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x05R\x06amount\"R\n" +
	"\x0fPaymentResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12%\n" +
	"\x0ecorrect_amount\x18\x02 \x01(\bR\rcorrectAmount\",\n" +
	"\fOfferRequest\x12\x1c\n" +
	"\trequester\x18\x01 \x01(\tR\trequester\"\xb3\x01\n" +
	"\rOfferResponse\x12\x1b\n" +
	"\thas_offer\x18\x01 \x01(\bR\bhasOffer\x12\x12\n" +
	"\x04loot\x18\x02 \x01(\x05R\x04loot\x12)\n" +
	"\x10success_franklin\x18\x03 \x01(\x05R\x0fsuccessFranklin\x12%\n" +
	"\x0esuccess_trevor\x18\x04 \x01(\x05R\rsuccessTrevor\x12\x1f\n" +
	"\vpolice_risk\x18\x05 \x01(\x05R\n" +
	"policeRisk\"K\n" +
	"\x0fDecisionRequest\x12\x1c\n" +
	"\trequester\x18\x01 \x01(\tR\trequester\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\",\n" +
	"\x10DecisionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"L\n" +
	"\vStarRequest\x12\x1c\n" +
	"\tcharacter\x18\x01 \x01(\tR\tcharacter\x12\x1f\n" +
	"\vpolice_risk\x18\x02 \x01(\x05R\n" +
	"policeRisk\"(\n" +
	"\fStarResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"+\n" +
	"\vStopRequest\x12\x1c\n" +
	"\tcharacter\x18\x01 \x01(\tR\tcharacter\"(\n" +
	"\fStopResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"j\n" +
	"\x12DistractionRequest\x12%\n" +
	"\x0erequired_turns\x18\x01 \x01(\x05R\rrequiredTurns\x12-\n" +
	"\x12assigned_character\x18\x02 \x01(\tR\x11assignedCharacter\"I\n" +
	"\x13DistractionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa2\x01\n" +
	"\fGolpeRequest\x12%\n" +
	"\x0erequired_turns\x18\x01 \x01(\x05R\rrequiredTurns\x12-\n" +
	"\x12assigned_character\x18\x02 \x01(\tR\x11assignedCharacter\x12\x1f\n" +
	"\vpolice_risk\x18\x03 \x01(\x05R\n" +
	"policeRisk\x12\x1b\n" +
	"\tbase_loot\x18\x04 \x01(\x05R\bbaseLoot\"C\n" +
	"\rGolpeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"-\n" +
	"\rStatusRequest\x12\x1c\n" +
	"\tcharacter\x18\x01 \x01(\tR\tcharacter\"\xb6\x01\n" +
	"\x0eStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12'\n" +
	"\x0fturns_completed\x18\x02 \x01(\x05R\x0eturnsCompleted\x12\x1f\n" +
	"\vtotal_turns\x18\x03 \x01(\x05R\n" +
	"totalTurns\x12#\n" +
	"\rcurrent_stars\x18\x04 \x01(\x05R\fcurrentStars\x12\x1d\n" +
	"\n" +
	"extra_loot\x18\x05 \x01(\x05R\textraLoot\"+\n" +
	"\vLootRequest\x12\x1c\n" +
	"\tcharacter\x18\x01 \x01(\tR\tcharacter\"-\n" +
	"\fLootResponse\x12\x1d\n" +
	"\n" +
	"final_loot\x18\x01 \x01(\x05R\tfinalLoot\"\xb7\x02\n" +
	"\vFinalReport\x12'\n" +
	"\x0fmission_outcome\x18\x01 \x01(\tR\x0emissionOutcome\x12\x1d\n" +
	"\n" +
	"total_loot\x18\x02 \x01(\x05R\ttotalLoot\x12#\n" +
	"\rmichael_share\x18\x03 \x01(\x05R\fmichaelShare\x12%\n" +
	"\x0efranklin_share\x18\x04 \x01(\x05R\rfranklinShare\x12!\n" +
	"\ftrevor_share\x18\x05 \x01(\x05R\vtrevorShare\x12!\n" +
	"\flester_share\x18\x06 \x01(\x05R\vlesterShare\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\x12)\n" +
	"\x10character_failed\x18\b \x01(\tR\x0fcharacterFailed\"*\n" +
	"\x0eReportResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xca\x02\n" +
	"\x0eMissionService\x12I\n" +
	"\x10StartDistraction\x12\x19.heist.DistractionRequest\x1a\x1a.heist.DistractionResponse\x127\n" +
	"\n" +
	"StartGolpe\x12\x13.heist.GolpeRequest\x1a\x14.heist.GolpeResponse\x12:\n" +
	"\vCheckStatus\x12\x14.heist.StatusRequest\x1a\x15.heist.StatusResponse\x127\n" +
	"\fGetFinalLoot\x12\x12.heist.LootRequest\x1a\x13.heist.LootResponse\x12?\n" +
	"\x0eReceivePayment\x12\x15.heist.PaymentRequest\x1a\x16.heist.PaymentResponse2\x89\x02\n" +
	"\rLesterService\x125\n" +
	"\bGetOffer\x12\x13.heist.OfferRequest\x1a\x14.heist.OfferResponse\x12B\n" +
	"\x0fConfirmDecision\x12\x16.heist.DecisionRequest\x1a\x17.heist.DecisionResponse\x12<\n" +
	"\x0fSendFinalReport\x12\x12.heist.FinalReport\x1a\x15.heist.ReportResponse\x12?\n" +
	"\x0eReceivePayment\x12\x15.heist.PaymentRequest\x1a\x16.heist.PaymentResponse2\x9a\x01\n" +
	"\x13NotificationService\x12A\n" +
	"\x16StartStarNotifications\x12\x12.heist.StarRequest\x1a\x13.heist.StarResponse\x12@\n" +
	"\x15StopStarNotifications\x12\x12.heist.StopRequest\x1a\x13.heist.StopResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_heist_proto_rawDescOnce sync.Once
	file_proto_heist_proto_rawDescData []byte
)

func file_proto_heist_proto_rawDescGZIP() []byte {
	file_proto_heist_proto_rawDescOnce.Do(func() {
		file_proto_heist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_heist_proto_rawDesc), len(file_proto_heist_proto_rawDesc)))
	})
	return file_proto_heist_proto_rawDescData
}

var file_proto_heist_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_heist_proto_goTypes = []any{
	(*PaymentRequest)(nil),      // 0: heist.PaymentRequest
	(*PaymentResponse)(nil),     // 1: heist.PaymentResponse
	(*OfferRequest)(nil),        // 2: heist.OfferRequest
	(*OfferResponse)(nil),       // 3: heist.OfferResponse
	(*DecisionRequest)(nil),     // 4: heist.DecisionRequest
	(*DecisionResponse)(nil),    // 5: heist.DecisionResponse
	(*StarRequest)(nil),         // 6: heist.StarRequest
	(*StarResponse)(nil),        // 7: heist.StarResponse
	(*StopRequest)(nil),         // 8: heist.StopRequest
	(*StopResponse)(nil),        // 9: heist.StopResponse
	(*DistractionRequest)(nil),  // 10: heist.DistractionRequest
	(*DistractionResponse)(nil), // 11: heist.DistractionResponse
	(*GolpeRequest)(nil),        // 12: heist.GolpeRequest
	(*GolpeResponse)(nil),       // 13: heist.GolpeResponse
	(*StatusRequest)(nil),       // 14: heist.StatusRequest
	(*StatusResponse)(nil),      // 15: heist.StatusResponse
	(*LootRequest)(nil),         // 16: heist.LootRequest
	(*LootResponse)(nil),        // 17: heist.LootResponse
	(*FinalReport)(nil),         // 18: heist.FinalReport
	(*ReportResponse)(nil),      // 19: heist.ReportResponse
}
var file_proto_heist_proto_depIdxs = []int32{
	10, // 0: heist.MissionService.StartDistraction:input_type -> heist.DistractionRequest
	12, // 1: heist.MissionService.StartGolpe:input_type -> heist.GolpeRequest
	14, // 2: heist.MissionService.CheckStatus:input_type -> heist.StatusRequest
	16, // 3: heist.MissionService.GetFinalLoot:input_type -> heist.LootRequest
	0,  // 4: heist.MissionService.ReceivePayment:input_type -> heist.PaymentRequest
	2,  // 5: heist.LesterService.GetOffer:input_type -> heist.OfferRequest
	4,  // 6: heist.LesterService.ConfirmDecision:input_type -> heist.DecisionRequest
	18, // 7: heist.LesterService.SendFinalReport:input_type -> heist.FinalReport
	0,  // 8: heist.LesterService.ReceivePayment:input_type -> heist.PaymentRequest
	6,  // 9: heist.NotificationService.StartStarNotifications:input_type -> heist.StarRequest
	8,  // 10: heist.NotificationService.StopStarNotifications:input_type -> heist.StopRequest
	11, // 11: heist.MissionService.StartDistraction:output_type -> heist.DistractionResponse
	13, // 12: heist.MissionService.StartGolpe:output_type -> heist.GolpeResponse
	15, // 13: heist.MissionService.CheckStatus:output_type -> heist.StatusResponse
	17, // 14: heist.MissionService.GetFinalLoot:output_type -> heist.LootResponse
	1,  // 15: heist.MissionService.ReceivePayment:output_type -> heist.PaymentResponse
	3,  // 16: heist.LesterService.GetOffer:output_type -> heist.OfferResponse
	5,  // 17: heist.LesterService.ConfirmDecision:output_type -> heist.DecisionResponse
	19, // 18: heist.LesterService.SendFinalReport:output_type -> heist.ReportResponse
	1,  // 19: heist.LesterService.ReceivePayment:output_type -> heist.PaymentResponse
	7,  // 20: heist.NotificationService.StartStarNotifications:output_type -> heist.StarResponse
	9,  // 21: heist.NotificationService.StopStarNotifications:output_type -> heist.StopResponse
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_heist_proto_init() }
func file_proto_heist_proto_init() {
	if File_proto_heist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_heist_proto_rawDesc), len(file_proto_heist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_heist_proto_goTypes,
		DependencyIndexes: file_proto_heist_proto_depIdxs,
		MessageInfos:      file_proto_heist_proto_msgTypes,
	}.Build()
	File_proto_heist_proto = out.File
	file_proto_heist_proto_goTypes = nil
	file_proto_heist_proto_depIdxs = nil
}
